steps:
# Build and test frontend
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', '.']
  dir: 'frontend'

# Build and test property service
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'services/property'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'services/property'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/property-service:$COMMIT_SHA', '.']
  dir: 'services/property'

# Deploy Cloud Run services
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'frontend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory'
  - '256Mi'
  - '--cpu'
  - '0.5'
  - '--max-instances'
  - '2'
  - '--set-env-vars'
  - 'NODE_ENV=staging'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'property-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/property-service:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--memory'
  - '256Mi'
  - '--cpu'
  - '0.5'
  - '--max-instances'
  - '2'
  - '--vpc-connector'
  - 'projects/$PROJECT_ID/locations/us-central1/connectors/vpc-connector'
  - '--set-env-vars'
  - 'NODE_ENV=staging'
  - '--set-secrets'
  - 'DATABASE_URL=property-service-secrets:database_url:latest'

# Deploy Cloud Functions
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'property-events'
  - '--runtime'
  - 'nodejs16'
  - '--trigger-topic'
  - 'property-events'
  - '--memory'
  - '256MB'
  - '--max-instances'
  - '2'
  - '--set-env-vars'
  - 'NODE_ENV=staging'
  - '--vpc-connector'
  - 'projects/$PROJECT_ID/locations/us-central1/connectors/vpc-connector'

# Monitoring setup
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'monitoring'
  - 'channels'
  - 'create'
  - '--display-name=staging-alerts'
  - '--type=email'
  - '--channel-labels=email_address=alerts@hexproperty.com'

# Alert policies
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'alpha'
  - 'monitoring'
  - 'policies'
  - 'create'
  - '--display-name=high-latency'
  - '--condition-filter=metric.type="run.googleapis.com/request_latencies"'
  - '--condition-threshold-value=2000'
  - '--condition-threshold-duration=300s'
  - '--notification-channels=staging-alerts'

images:
- 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/property-service:$COMMIT_SHA'

timeout: '1800s'

options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: '100'
  logStreamingOption: STREAM_ON
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _REGION: us-central1
  _ENV: staging
