export enum PropertyStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    MAINTENANCE = 'MAINTENANCE',
    UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
    PENDING_APPROVAL = 'PENDING_APPROVAL'
}
