openapi: 3.0.0
info:
  title: API Documentation Template
  version: 1.0.0
  description: |
    Template for API endpoint documentation

paths:
  /{endpoint}:
    parameters:
      - name: endpoint
        in: path
        required: true
        schema:
          type: string
        description: The endpoint path

    get:
      summary: Get Operation
      description: Detailed description of the GET operation
      parameters:
        - name: param1
          in: query
          schema:
            type: string
          description: Parameter description
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  property1:
                    type: string
                    description: Property description
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

    post:
      summary: Create Operation
      description: Detailed description of the POST operation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                property1:
                  type: string
                  description: Property description
      responses:
        '201':
          description: Successfully created
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
        details:
          type: object
          description: Additional error details

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
